
version: "3"

services:

  #
  # Splunk hits SEPTA's API regularly and ingests the data it gets.
  #
  splunk:
    build:
      context: .
      dockerfile: "Dockerfile-splunk"
    restart: "always"
    #privileged: true
    volumes:
      - .:/mnt
      #
      # Our Splunk app
      #
      - ./splunk-apps/septa-stats:/opt/splunk/etc/apps/septa-stats
      - ./splunk-apps/timewrap:/opt/splunk/etc/apps/timewrap
      #
      # Our Splunk data
      #
      - ./splunk-data/septa-stats:/opt/splunk/var/lib/splunk/septa_analytics/
    ports:
      - 8001:8000
    environment:
      - TZ=EST5EDT


  #
  # Set up our web server
  #
  web:
    image: nginx:alpine
    ports: 
      - 8002:80
    restart: "always"
    volumes: 
      - .:/mnt
      - ./splunk-apps/septa-stats/htdocs/:/htdocs
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=EST5EDT


  #
  # Set up PHP running in FCGI mode
  #
  php:
    image: php:7.2.8-fpm
    #image: php:5.6.37-fpm
    restart: "always"
    volumes: 
      - .:/mnt
      - ./splunk-apps/septa-stats/htdocs/:/htdocs
    environment:
      - TZ=EST5EDT


  #
  # Set up Redis
  #
  redis:
    image: redis:4-alpine
    restart: "always"
    volumes: 
      - .:/mnt
      - ./redis-data:/data
    environment:
      - TZ=EST5EDT
    command: redis-server /mnt/redis.conf


  backup:
    build:
      context: .
      dockerfile: "Dockerfile-backup"
    restart: "always"
    privileged: true
    volumes:
      - .:/mnt
    environment:
      - TZ=EST5EDT
      #
      # This *MUST* end in a slash!
      #
      - S3=s3://dmuth-septa-stats/backups-dev/
      - LOOP_SECONDS=900
      #- LOOP_SECONDS=3 # Debugging
      - YESTERDAY_BACKUP_INTERVAL=4



