
version: "3"

services:

  #
  # Splunk hits SEPTA's API regularly and ingests the data it gets.
  #
  splunk:
    build:
      context: .
      dockerfile: "Dockerfile-splunk"
    restart: "always"
    privileged: true
    volumes:
      - .:/mnt
      #
      # Our Splunk app
      #
      - ./splunk-apps/septa-stats:/opt/splunk/etc/apps/septa-stats
      - ./splunk-apps/timewrap:/opt/splunk/etc/apps/timewrap
      #
      # Our Splunk data
      #
      - ./splunk-data/septa-stats:/opt/splunk/var/lib/splunk/septa_analytics/
    ports:
      - 8001:8000
    environment:
      - TZ=EST5EDT


