
version: "3"

services:

  #
  # Splunk hits SEPTA's API regularly and ingests the data it gets.
  #
  splunk:
    build:
      context: .
      dockerfile: "Dockerfile-splunk"
    restart: "always"
    #privileged: true
    volumes:
      - .:/mnt
      #
      # Our Splunk app
      #
      - ./splunk-apps/septa-stats:/opt/splunk/etc/apps/septa-stats
      - ./splunk-apps/timewrap:/opt/splunk/etc/apps/timewrap
      #
      # Our Splunk data
      #
      - ./splunk-data/septa-stats:/opt/splunk/var/lib/splunk/septa_analytics/
    ports:
      - 8001:8000
    environment:
      - TZ=EST5EDT


  #
  # Set up our web server
  #
  web:
    image: nginx:alpine
    ports: 
      - 8002:80
    restart: "always"
    volumes: 
      - .:/mnt
      - ./splunk-apps/septa-stats/htdocs/:/htdocs
      - ./nginx.conf:/etc/nginx/conf.d/default.conf


  #
  # Set up PHP running in FCGI mode
  #
  php:
    image: php:7.2.8-fpm
    #image: php:5.6.37-fpm
    restart: "always"
    volumes: 
      - .:/mnt
      - ./splunk-apps/septa-stats/htdocs/:/htdocs


  #
  # Set up Redis
  #
  redis:
    image: redis:4
    restart: "always"
    volumes: 
      - .:/mnt
      - ./redis-data:/data



